### ISSUE TITLE
Wireless charging fails

### ISSUE THREAD

**Issue by Bsoupe** [HelloVolla/ubuntu-touch-beta-tests#81] opened 2020-12-13 18:35 UTC
OTA-14
Used Wireless Charger: https://udoq.de/product/drahtlos-adapter/

After inserting the device, the fast boot mode is activated but the device will not charge!

**Steps to reproduce the bug**

1. insert device (switched off / empty battery)
2. wait a little
3. display show "fast boot mode" in the left lower corner
4. you have to keep the power button pressed for a longer time to start the device again

**Expected behavior**
The device should have the same behavior like charging with a connect by a cable.

Notice: This behavior did not occur when the device was switched on! In this case wireless charging works fine!

**Comment by JamiKettunen** [comment] 2020-12-13 18:51
Duplicate of #37, so closing this. Interesting to see people using wireless chargers though :)

**Closed by JamiKettunen** 2020-12-13 18:51 UTC
Labels: duplicate

**Comment by Bsoupe** [comment] 2020-12-13 19:06
Oh, sorry I didn't noticed this!
