### ISSUE TITLE
USSD doesn't work

### ISSUE THREAD

**Issue by Danct12** [HelloVolla/ubuntu-touch-beta-tests#44] opened 2020-09-11 12:04 UTC
USSD (aka Unstructured Supplementary Service Data) does not work on Ubuntu, when requesting USSD from the dialer app, it stuck at "Please wait..."

USSD is really important as it is used for things such as switching data plans, add funds to account and so on.

This is tested on Ubuntu (2020-09-11/2 - devel)

**Comment by JamiKettunen** [comment] 2020-09-11 19:42
Duplicate of #38.

**Closed by JamiKettunen** 2020-09-11 19:42 UTC
