### ISSUE TITLE
Swiping in application fan wonky

### ISSUE THREAD

**Issue by NeoTheThird** [HelloVolla/ubuntu-touch-beta-tests#14] opened 2020-07-06 13:54 UTC
The multitasking sliding gesture is not properly working on my vollaphone. This is a behavior i have not seen in UT, so i'm assuming it's a porting issue. Video: https://www.file-upload.net/download-14177540/video20200706_154428799.mp4.html

**Comment by Stevie00911** [comment] 2020-07-23 15:11
Same behavior on my vollaphone. I reach to close apps only if I slide verry fast down the screen.

**Comment by tyg3rpro** [comment] 2020-08-04 13:50
I have this issue as well, I have to hold my finger on the app for a second or two then slowly slide up, otherwise it thinks Im trying to slide to the right.  I think it might be either a sensitivity issue, or possibly interference from the screen protector.  I wonder if anyone has pulled that off and tried?

**Comment by wurzer** [comment] 2020-08-30 00:44
Isn't this an intended behavior of Ubuntu Touch?

**Comment by tyg3rpro** [comment] 2020-08-30 00:59
> Isn't this an intended behavior of Ubuntu Touch?

This is not the intended behaviour of the app fan, the way its supposed to function is you swipe in from the right, and it shows the apps in the app fan, then when you swipe up it closes the apps, what is happening currently is you swipe in from the right which works as expected, but when you try to swipe up, unless you do it slowly it sees the gesture as a swipe left, at least for my device, which is not the intended behaviour.

**Comment by Danct12** [comment] 2020-09-09 02:45
> I have this issue as well, I have to hold my finger on the app for a second or two then slowly slide up, otherwise it thinks Im trying to slide to the right. I think it might be either a sensitivity issue, or possibly interference from the screen protector. I wonder if anyone has pulled that off and tried?

It is not device specific, I've tested it on another device that uses Halium 9 (Redmi Note 7) and the same issue happened there.

**Comment by rubencarneiro** [comment] 2020-09-16 18:38
> The multitasking sliding gesture is not properly working on my vollaphone. This is a behavior i have not seen in UT, so i'm assuming it's a porting issue. Video: https://www.file-upload.net/download-14177540/video20200706_154428799.mp4.html

Does this behavior does also happens on pinephone?

**Comment by wurzer** [comment] 2020-09-17 07:12
you can tap on an open app, hold one second and swipe up.

**Comment by rubencarneiro** [comment] 2020-09-17 10:18
> you can tap on an open app, hold one second and swipe up.

Yeah but thats not how it shphld work.

**Comment by NeoTheThird** [comment] 2020-09-23 12:47
Something is definitely not right, it is not how multitasking is supposed to feel. If it works correctly, the app is glued to your finger and smoothly moves with it without delay.

**Comment by Stevie00911** [comment] 2020-10-02 11:00
This behaviour with this "one second of holding" is still a no go.
On the BQ Aquaris phone with UBports Ubuntu Touch the close swiping was smooth like on an iphone or an Android phone.
Ubuntu version 16.04. (2020-10-02)

**Comment by JamiKettunen** [comment] 2020-10-09 16:10
Swiping away apps now seems to work without such strange issues as of development channel build `2020-10-09/2`, so closing this issue :)

**Closed by JamiKettunen** 2020-10-09 16:10 UTC
Labels: bug
