### ISSUE TITLE
Phone Radio Cellular data setting "2G/3G/4G" does not connect to the Internet

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#23] opened 2020-07-24 10:06 UTC
The Phone Radio Cellular data setting "2G/3G/4G" does not connect to the Internet.

Even after a reboot, whitch is actually allways needed for changing Phone Radio settings, the "2G/3G/4G" option is not working.
No 2G, no 3G and no 4G (LTE) is activated.

The small icon shown on the right side from the Telecom provider info shows in 2G mode a "2G" and in 3G mode a "3G" Text.
In the "2G/3G/4G" setting the icon shows only a "L" 

Ubuntu Version 16.04. (2020-07-24)

**Comment by areyoudeveloper** [comment] 2020-08-04 13:14
Maybe need config apn

**Comment by wurzer** [comment] 2020-08-29 17:14
You may need to set the ATM settings.

**Comment by Stevie00911** [comment] 2020-09-07 14:18
Ok fine, but where can I set up the ATM settings on the vollaphone?

**Comment by TellingBerto** [comment] 2020-09-12 10:28
In addition the indicator "L" is not replaced by e.g. "3G" when the user switches back from LTE to 3G.

**Comment by TellingBerto** [comment] 2020-09-19 11:57
Please be aware of the announcement (18.09.2020) of Deutsche Telekom that they will not support 3G after 30.06.2021. Same for Vodafone. Only O2 will provide this until 2022.

**Comment by JamiKettunen** [comment] 2020-10-14 18:36
I was able to reproduce the original issue as per the title ("Phone Radio Cellular data setting "2G/3G/4G" does not connect to the Internet") when continuing to switch between 2G, 3G and LTE options, but not anymore as of Development channel build `2020-10-14/2`.
@Stevie00911 could you re-test this as well? I think this issue can be closed now.

**Comment by TellingBerto** [comment] 2020-10-14 19:22
version 2020-10-14/2
channel dev

**Retest**
Result: 
Not working for LTE, no cellular data. 
Open Morph.
Enter: www.google.com
Result: Error: net:ERR_NAME_RESOLUTION_FAILED 
Indicator "L" displayed next to provider (network settings).
Sometimes indicator for cellular data not displayed in indicator bar.

Switch form LTE to 2G/3G: 
Working for 2G/3G, cellular data. 
Open Morph.
Enter: www.google.com
Page is displayed.
Indicator "3G" displayed next to provider (network settings).
Indicator for cellular data "3G" is displayed in indicator bar.

**Comment by TellingBerto** [comment] 2020-10-30 07:22
version 2020-W44
channel: RC

Retest

**Result:**
Issue persists, not working for LTE. No cellular data, no access to internet.

Steps processed:
1. Setting for celluar data: 2G/3G/4G activated.
-> Indicator "L" displayed next to provider (network settings) and in indicator bar.
2. Open Morph.
3. Enter: www.google.com
Result: Error: net:ERR_NAME_RESOLUTION_FAILED

**Remarks:** 
Sometimes indicator for cellular data not displayed in indicator bar.
Reboot does not solve the issue.

**Comment by wurzer** [comment] 2020-10-30 08:14
I definitely can''t reproduce this issue. 

1. Change to the RC channel
2. Set the APN Settings for your carrier.

Please also note the frequency bands and check, whether the device supports any of your carrier's frequency bands. Are you located in the US?

**Comment by TellingBerto** [comment] 2020-10-30 19:08
version 2020-W44
**channel: RC**

Nope. Can´t provide a success story.
Verified with Deutsche Telekom and SwissCom.
Currently located in Germany.

APN-Settings for the provider are set.

UMTS: 
Result: Working, internet access. 

LTE: 
Result: Not working, probably internet access. Error: net::ERR_NAME_RESOLUTION_FAILED
Like described above, even with a connection, the speed of the connection is not what can be expected with LTE.

LTE is available, checkt with IPHONE, Windows Phone, Android Phone. 

Is there a log I can/should provide?

**Comment by wurzer** [comment] 2020-10-30 23:08
Unfortunately I can't reproduce it. Did you check the option "2G/3G/4G" in the Network settings? I just made a speed test in the Morph browser I have 16 MBit with Blau.de. 

Did you use the same SIM card for your test with the other devices?

**Comment by TellingBerto** [comment] 2020-10-31 19:21
Uh, this is not good. 
Ok, Blau is using a different type of network compared to Telekom. 
What kind of setting should be checked here? Could you please provide a screenshot? 
Manually entering the APN information does not work. New, manual entry e.g. for LTE can not be saved.
And details e.g. for "internet" are not available like Ruben mentioned in #64.
Yes, of course, SIM was always the identical. 
Tell me how to provide a log & I´ll try to provide it.

**Comment by deyanyosifov** [comment] 2021-01-02 23:46
I have some similar problems. I have two SIM cards and 4G LTE works only with the SIM card that is inserted in slot 1, no matter which. It frequently happens that when I try to initiate a call through the SIM card in slot 2, I either get a message "No SIM card selected" or it appears that the phone is dialling the number but I hear no signal at all (in both cases the network availability indicator shows full signal strength). In such cases, when I restart the phone usually the problem disappears and I am able to make a call but some time later the problem appears again. Sometimes, after a restart I get prompted to enter the PIN code only for the SIM card in slot 1 and in this case the SIM card in slot 2 is afterwards not even listed in the menu. Yesterday, the phone said there was no data connection when I tried to browse the internet (SIM card 1) and after a restart it worked again.

**Comment by UniversalSuperBox** [comment] 2021-02-04 22:45
I believe this issue is related to https://github.com/ubports/ubuntu-touch/issues/1657, and can be closed in favor of that other report on the main Ubuntu Touch tracker.

**Comment by JamiKettunen** [comment] 2021-03-14 15:34
As per Dalton's message above I'll go ahead and close this for now; there's also been a [patch that was added to ofono](https://github.com/ubports/ofono/commit/f9e950807891c2650dcbdb2dd272ef2292e06f44) which should now default to IPv4 on **new installations of Ubuntu Touch**. Existing users facing the issue still may need to run `/usr/share/ofono/scripts/set-context-property 0 Protocol IP` from a terminal to switch the internet context protocol to IPv4.

**Closed by JamiKettunen** 2021-03-14 15:34 UTC
Labels: question
