### ISSUE TITLE
MTP does not work

### ISSUE THREAD

**Issue by NeoTheThird** [HelloVolla/ubuntu-touch-beta-tests#12] opened 2020-07-05 22:26 UTC
No file transfer possible

**Comment by JamiKettunen** [comment] 2020-08-26 18:30
I've written up a gist with details on how to make MTP work for now:
https://gist.github.com/JamiKettunen/6f5f15c75ed85feb4bad58a89e705a7d

It's very ugly and inconvenient, but hey, it's something!

**Comment by JamiKettunen** [comment] 2020-08-30 10:57
MTP should now work after OTA to build 2020-08-30. For future reference, commits [7a0358f](https://github.com/HelloVolla/android_device_volla_yggdrasil/commit/7a0358fedc315d3c59a6b2165682bd0a229578ed)...[a6bedb9](https://github.com/HelloVolla/android_device_volla_yggdrasil/commit/a6bedb93bd42516ab261c8616a2ad7ed63879357) (4 in total) made it work.

**Comment by wurzer** [comment] 2020-10-26 04:20
Please Check, whether you have this problem if you switch to the release candidate channel.

**Comment by Stevie00911** [comment] 2020-10-26 08:22
I switched to release candidate 16.04 (2020-W43) now and I confirm that the "Phone" device is not more present in Windows 10 device manager and Explorer.
After putting the USB cable in and out of the phone the device manager "flickers", but shows no new icon.
Since the beginning of this topic: the green charging icon is not shown in the notification hub, however the phone is charged.

**Comment by TellingBerto** [comment] 2020-10-26 09:45
Is the absence of the ability to connect via USB (in development channel) made by purpose or by accident? (2020-10-25/2, channel dev)
What is the target state?
Thx for your clarification.

**Comment by wurzer** [comment] 2020-10-26 11:44
We have checked a USB connection for MTP successfully. Which operating system are you use to connect the Volla Phone to your device? Did you switch to the release candidate channel to have a stable system?

**Comment by Stevie00911** [comment] 2020-10-26 13:09
Operating system: Windows 10 Pro, 2004
Volla Phone: 16.04 release candidate (2020-W43), no other actual OTA available

**Comment by JamiKettunen** [comment] 2020-10-30 19:38
There was a regression on initramfs level which has now been resolved, and MTP is working again perfectly fine as of development channel update `2020-10-30/2` and I think a similar patch was also pushed to RC channel.
Please retest this and comment back so I can close the issue once again!

Additionally you may want to check #24 in case you still can't get MTP working on Windows.

**Closed** 2020-10-30 22:52 UTC
