### ISSUE TITLE
Connection icon not updated after flight mode in indicator bar

### ISSUE THREAD

**Issue by TellingBerto** [HelloVolla/ubuntu-touch-beta-tests#67] opened 2020-11-07 12:32 UTC
Hello,

phone has been booted, PIN for SIM has been entered. Icon for connection is displayed as expected in indicator bar. Calls can be placed/received.

Problem: After DE-activation of flight mode, the connection icon is remaining with the wrong symbol, even after hours.

**Steps processed:**
1. Boot device and enter SIM PIN. -> Carrier registration is taking place and calls can be placed / received.
2. Activate flight mode. -> Connection icon is set to the appropriate symbol, no calls can be placed/received (as expected).
3. Deactivat flight mode. -> Icon remain with the wrong symbol. Calls can be placed/received. 
(Waiting for hours, placing or receiving calls does not affect the icon).

Icon after deactivated flight mode:

![image](https://user-images.githubusercontent.com/61089736/98441073-c9895480-20fc-11eb-9dae-17a20b0901a5.png)

Icon several hours later:

![image](https://user-images.githubusercontent.com/61089736/98441192-12d9a400-20fd-11eb-983c-15bf99ac580d.png)

**Result:**  Icon for connection is not updated correctly after flight mode.

UT: 2020-11-06, Channel: DEV

**Comment by JamiKettunen** [comment] 2020-12-09 13:44
I cannot reproduce this after several retries on dev channel build `2020-12-09/??`; perhaps output from `tail -f /var/log/syslog` could help us with solving this? Try running that on a terminal (from `adb shell`, `ssh` or otherwise on-device) **before** toggling Flight Mode on and back off to try and catch some intel as to why it might not be updating the indicator status.
You can upload the log here or [a paste service](https://paste.ubuntu.com/).

**Comment by tbuen** [comment] 2021-01-08 21:28
Hello, I have the same problem here. Reproducible with stable channel as well as with dev 2021-01-08.

**Comment by gbdomubpkm** [comment] 2021-03-11 04:52
Not reproductible for me (tests between RC 9 and RC 11).

**Comment by JamiKettunen** [comment] 2021-03-14 15:28
@TellingBerto @tbuen can you attempt reproducing this under the latest RC channel build? This should hopefully be fixed in OTA-16 thanks to [NotKit's binder patch](https://github.com/HelloVolla/android_kernel_volla_mt6763/commit/ade5d98), but could also be a different issue.

**Comment by tbuen** [comment] 2021-03-14 15:51
Hi @JamiKettunen , yes this seems to be fixed in the RC, just tested and it's working fine now :+1:

**Comment by JamiKettunen** [comment] 2021-03-25 09:53
As I've not heard back from Berto for 2 weeks soon I'll close this issue now. If you're still experiencing this please comment here or open a new issue! :)

**Closed by JamiKettunen** 2021-03-25 09:53 UTC
Labels: question
