### ISSUE TITLE
Starting charging from power off will cause booting to fastboot mode

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#37] opened 2020-09-02 18:05 UTC
If the phone battery fully discharges and then is plugged in to charge, the phone will instead boot to fast boot. Work around for this is to disconnect the cable, reboot, let the phone boot to OS and then plug in to charge.

**Comment by mokmeister** [comment] 2020-09-02 18:07
It has been suggested that it may be a porting issue where the port is missing offline charging support.

**Comment by JamiKettunen** [comment] 2020-09-14 14:19
It should be noted that this happens always when the phone is powered on by plugging it to a power source (even if it isn't a computer); @NotKit has suggested that the device should be made to always boot Ubuntu Touch for now until support for offline charging is added.

**Comment by gbdomubpkm** [comment] 2020-12-04 17:31
Hello.
Received Volla yesterday (great smartphone) and first uses (bug reports coming soon).
First charge (I didn't know if the battery was totally full): this bug is still there (after update RC 2020-W49/2): any progress? 
My immediate solution was to make a forced shutdown (power button held down) to exit fastboot mode.

**Comment by JamiKettunen** [comment] 2020-12-04 17:45
@gbdomubpkm https://github.com/Halium/initramfs-tools-halium/pull/22 will fix this whenever it gets merged.

**Comment by gbdomubpkm** [comment] 2020-12-04 18:13
@JamiKettunen Thank you for the concerned link. This would be great for OTA-15 !

**Comment by gbdomubpkm** [comment] 2021-02-12 01:47
! will be happy not to see fastboot in this case !  😉

**Comment by JamiKettunen** [comment] 2021-03-24 15:45
Now that the pull request is merged, the fix should be in tomorrow's Development channel update. I'll test it then and close this if the issue is fixed.

**Comment by JamiKettunen** [comment] 2021-03-25 09:59
I've confirmed that on Development channel build `2021-03-25` now trying to enter charging mode reboots into Ubuntu Touch instead (a much better alternative for e.g. fast charging than rebooting into into fastboot mode after failing to boot the charging UI). There's still some work to do here to actually fix the charging mode, but for the end users this should be a solid workaround for now.

**Closed by JamiKettunen** 2021-03-25 09:59 UTC
Labels: bug

**Comment by mardy** [comment] 2021-04-02 18:17
Thanks for your work on this, Jami! Do we have a bug then for fixing this for good, that is reboot into charging mode? I could try to help, if you give me some hints at what needs to be done.

**Comment by gbdomubpkm** [comment] 2021-05-06 18:11
I discovered today that this issue seems fully solved : in last RC, there is now real charging with starting power off.
Thanks to the developper(s) involved. 👍

**Comment by gbdomubpkm** [comment] 2021-07-07 00:33
Charging from power off seems to heat up the back of the phone a lot currently (RC 22) :  is this a normal effect? This is much less the case when charging from smartphone on.
