### ISSUE TITLE
No APN configurations

### ISSUE THREAD

**Issue by rubencarneiro** [HelloVolla/ubuntu-touch-beta-tests#64] opened 2020-10-31 17:00 UTC
There are no apn configuration for the provider
So this is avaible be default on Nexus 5, Meizu Pro 5, fairphone 2 etc.

uncommenting  $(call inherit-product, vendor/lineage/config/common_full_phone.mk) on lineage_yggdrasil.mk will add apns.conf since it will also call telephony.mk

![screenshot20201031_165949399](https://user-images.githubusercontent.com/40370995/97785038-9f82e000-1b9a-11eb-8e91-8e2fb405a04b.png)
![screenshot20201031_165943855](https://user-images.githubusercontent.com/40370995/97785039-a0b40d00-1b9a-11eb-9df1-cc52190f8334.png)
![screenshot20201031_165938342](https://user-images.githubusercontent.com/40370995/97785040-a14ca380-1b9a-11eb-8581-517d691ebba9.png)

**Comment by wurzer** [comment] 2020-10-31 21:10
I cannot reproduce this issue. Could you enter the APN settings and test data connection?
Which provider do you use?

**Comment by rubencarneiro** [comment] 2020-10-31 22:07
> I cannot reproduce this issue. Could you enter the APN settings and test data connection?
> Which provider do you use?
Vodafone PT

6

**Comment by rubencarneiro** [comment] 2020-10-31 22:10
> I cannot reproduce this issue. Could you enter the APN settings and test data connection?
> Which provider do you use?

Vodafone Portugal, do you have your apn settings on your provider?

**Comment by wurzer** [comment] 2020-10-31 22:23
Sure, I have provider specific APN settings on my Volla Phone with UT. 
If you enter the APN settings, you need to define one for Internet and another for MMS. 
I found this for Vodafone Portugal: https://apnsettings.gishan.net/apn/419/portugal/vodafone-pt
It may also help to reset the APN settings first.
I have also a Klarmobil (Telefonica) and Deutsche Telekom SIM card, but both have other APN settings than your provider either. 
Please assign carefully the values to the correct keys. The first time I mixed up some assignments.

**Comment by rubencarneiro** [comment] 2020-11-01 00:13
> Sure, I have provider specific APN settings on my Volla Phone with UT.
> If you enter the APN settings, you need to define one for Internet and another for MMS.
> I found this for Vodafone Portugal: https://apnsettings.gishan.net/apn/419/portugal/vodafone-pt
> It may also help to reset the APN settings first.
> I have also a Klarmobil (Telefonica) and Deutsche Telekom SIM card, but both have other APN settings than your provider either.
> Please assign carefully the values to the correct keys. The first time I mixed up some assignments.

Actually is not suppose to you have yo rnter that definitions, thats why a file called apns.conf.xml exist, i can show that apns are already configured on devices like nexus 5, fairphone 2, oneplus one, meizu pro 5 etc. These fields are already filled by apns.conf.xml info

**Comment by rubencarneiro** [comment] 2020-11-01 12:19
This is my Pro5 as youcan see apn is already configured.

![screenshot20201101_121531169](https://user-images.githubusercontent.com/40370995/97802594-79ae1780-1c3c-11eb-9c3c-c1a208b25b57.png)
![screenshot20201101_121537996](https://user-images.githubusercontent.com/40370995/97802595-7a46ae00-1c3c-11eb-8ca1-d86b0b4be794.png)
![screenshot20201101_121548270](https://user-images.githubusercontent.com/40370995/97802596-7adf4480-1c3c-11eb-9864-64a059502093.png)
![screenshot20201101_121557582](https://user-images.githubusercontent.com/40370995/97802598-7b77db00-1c3c-11eb-9375-c6b3cb84522c.png)

**Comment by Flohack74** [comment] 2020-11-23 19:26
Will be fixed by https://gitlab.com/ubports/core/rootfs-builder-debos/-/merge_requests/18

**Comment by JamiKettunen** [comment] 2020-12-07 14:42
As the [referenced PR](https://gitlab.com/ubports/core/rootfs-builder-debos/-/merge_requests/18) is now merged, I tested this and it seems to fetch APN settings on it's own now :) RC and Development channels have the update currently so I'll close this issue now; please comment here or create a new issue as needed!

**Closed by JamiKettunen** 2020-12-07 14:42 UTC
