### ISSUE TITLE
Instability of GSM Carrier Network (Canada Rogers / Fido)

### ISSUE THREAD

**Issue by wayneoutthere** [HelloVolla/ubuntu-touch-beta-tests#53] opened 2020-10-03 12:12 UTC
I have used, as my daily driver, the following devices running Ubuntu Touch for the last few years: Nexus 4, Nexus 5, Fairphone2 and now trying Volla.

I am using a sim card with a company called Fido (in Canada) on one of the largest networks owned by Rogers.   The network is GSM.

While using the Nexus 4 and Nexus 5 (Devices sold regularly in North America) the quality of normal cellular calls is basically perfect (no complaints).

However, while using the Fairphone2 and Volla, there is a very strange behaviour and 'extreme inconsistency' of experience.

## The experience

* Call starts and goes well for usually a minute or two, sometimes longer
* A 'crackling' sound quality begins
* The UT user cannot hear the person speaking (sound starts dropping)
* The other party seems to still be able to hear the UT user while this is happening
* Eventually no sound at all
* Finally the call drops

## Some other things I've noted related to this

* The above poor experience seems to happen much more when approaching cell phone towers
* The above experience happens in 'weaker cell zone areas' which is expected (but it doesn't happen with Nexus 5 in these areas)
* Any SMS messages sent with photos / images / MMS are missed (however, this is probably my own APN settings - I have not spent much time on this issue since I don't care)

## Conclusion
Unfortunately the experience is so inconsistent / poor that I cannot continue to use the device as a daily driver (I have a business). It's 'almost' good enough, but not quite - I tried! :)  I'm ready to daily drive again and help test this on weekends though any time.

**Comment by JamiKettunen** [comment] 2020-10-14 18:24
I wonder if the GSM network stability issue is related to #55 since that should now be fixed in latest builds. Let's hope that is the case as otherwise this sounds like it would be very difficult to debug.

**Comment by wurzer** [comment] 2020-10-25 15:12
Can you check, whether the other devices are connected to a different network? Maybe the Volla Phone is connecting to a different network because od different supported frequency bands.

**Comment by wayneoutthere** [comment] 2020-10-26 00:11
It's the same network, same SIM card.  
I haven't tested in a few weeks though.  It looks like some stuff above has been improved... I will try to use it as a daily driver for a business day very soon.

**Comment by TartanSpartan** [comment] 2020-12-08 07:33
@wayneoutthere I think @wurzer is saying, perhaps your Volla is connecting to a 2G frequency whereas your N5 may be connecting to H (3G) or L (4G).

**Comment by wurzer** [comment] 2020-12-09 11:18
I think, G3 or G4 should be available in Canada for the Volla Phone:

GSM / 2G: 850 / 900 / 1800 / 1900 MHz, 
UMTS / 3G: 900 / 2100 MHz, 
FDD / LTE / 4G: 800 / 850 / 900 / 1800 / 2100 / 2600 MHz

**Comment by JamiKettunen** [comment] 2020-12-10 14:16
In case you've not tested this yet, please check things out on the stable channel; something has gone wrong with cellular things in devel and by extension RC update channels and the issue(s) still need to be tracked down.

**Comment by I-Cat** [comment] 2021-04-19 22:26
> I have used, as my daily driver, the following devices running Ubuntu Touch for the last few years: Nexus 4, Nexus 5, Fairphone2 and now trying Volla.
> 
> I am using a sim card with a company called Fido (in Canada) on one of the largest networks owned by Rogers. The network is GSM.
> 
> While using the Nexus 4 and Nexus 5 (Devices sold regularly in North America) the quality of normal cellular calls is basically perfect (no complaints).
> 
> However, while using the Fairphone2 and Volla, there is a very strange behaviour and 'extreme inconsistency' of experience.
> 
> ## The experience
> * Call starts and goes well for usually a minute or two, sometimes longer
> * A 'crackling' sound quality begins
> * The UT user cannot hear the person speaking (sound starts dropping)
> * The other party seems to still be able to hear the UT user while this is happening
> * Eventually no sound at all
> * Finally the call drops
> 
> ## Some other things I've noted related to this
> * The above poor experience seems to happen much more when approaching cell phone towers
> * The above experience happens in 'weaker cell zone areas' which is expected (but it doesn't happen with Nexus 5 in these areas)
> * Any SMS messages sent with photos / images / MMS are missed (however, this is probably my own APN settings - I have not spent much time on this issue since I don't care)
> 
> ## Conclusion
> Unfortunately the experience is so inconsistent / poor that I cannot continue to use the device as a daily driver (I have a business). It's 'almost' good enough, but not quite - I tried! :) I'm ready to daily drive again and help test this on weekends though any time.

The proper modem has to be flashed.
Make sure you IMEI is registered on Fido's network because they have a security thing where 
They boot u off there server if the IMEI is not recognized in there system.
Also Fido only supports certain network bands...  Not to get too detailed but..
|--
For the developers the bands are
2G (GSM/EDGE)	850	 = B5
3G (UMTS/HSPA)	850	= B5
4G LTE	700 MB           = B12
850 MHz	                  = B5
1900 MHz	                  = B2, B25
1700/2100 MHz (AWS) = B4, B66
2600 MHz	                   = B7
--

At the moment 
Fido / Rogers is down... but...
Try typing in what I got in my screen shots.
(I am located in Ontario Canada)
My Lg G4 didn't work well untill I flashed the modem properly.


![Screenshot_20210419_180641_com android settings](https://user-images.githubusercontent.com/68921721/115309352-27a17580-a13a-11eb-920e-3d7b82133a23.jpg)
![Screenshot_20210419_180657_com android settings](https://user-images.githubusercontent.com/68921721/115309355-27a17580-a13a-11eb-946c-4e3825f2bcbf.jpg)

**Comment by wurzer** [comment] 2021-04-20 07:28
I can confirm, that I have a stable connection to the cellular network including MMS. No network lost (Vodafone, Telekom and E-Plus via Klarmobil and Blau in Germany tested)

For one SIM card respectively network carrier, I have tested I had to enter the APN settings for MMS. In some cases you need to restart the device. Then sending and receiving MMS is working. 

It's important to have the stable OTA-16 release on the device. In the past I could reproduce, that I can't hear the person I'M talking in a phone call. I can't reproduce it any more.

**Comment by I-Cat** [comment] 2021-05-01 02:48
> I can confirm, that I have a stable connection to the cellular network including MMS. No network lost (Vodafone, Telekom and E-Plus via Klarmobil and Blau in Germany tested)
> 
> For one SIM card respectively network carrier, I have tested I had to enter the APN settings for MMS. In some cases you need to restart the device. Then sending and receiving MMS is working.
> 
> It's important to have the stable OTA-16 release on the device. In the past I could reproduce, that I can't hear the person I'M talking in a phone call. I can't reproduce it any more.


Cool I hope I helped.

**Comment by wurzer** [comment] 2021-05-23 21:57
Should be solved with release OTA-16 and newer

**Closed by wurzer** 2021-05-23 21:57 UTC
Labels: question
