### ISSUE TITLE
Changes to rootfs are not saved

### ISSUE THREAD

**Issue by luka177** [HelloVolla/ubuntu-touch-beta-tests#42] opened 2020-09-08 08:15 UTC
You can remount rootfs
```
sudo mount -o rw,remount /
```
And you can even modify it, but after reboot you understand that nothing changed. For me this bug is critical, and system becoming useless .

**Comment by luka177** [comment] 2020-09-08 08:20
This can be fixed with custom lk, but need some better fix.

**Comment by Flohack74** [comment] 2020-09-08 18:58
Sorry this is not true, of course changes to the rootfs are persisted. Please describe exactly what you want to do. Without the precise statements for what you wanted to modify nobody can reproduce it.

**Comment by wurzer** [comment] 2020-09-12 11:29
Could you explain the use case? The relevance for consumer is not clear for me.

**Comment by NeoTheThird** [comment] 2020-09-23 12:50
I think we can close this, as it's not specific to the vollaphone, and it is the intended behavior. Changes to the rootfs do in fact persist, but a full (ie non-delta) update will overwrite them. The writable mount can be persisted by setting a flagfile, for example using uttweaktool.

**Closed by NeoTheThird** 2020-09-23 12:50 UTC
