### ISSUE TITLE
Automatic Brightness option missing

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#20] opened 2020-07-23 15:42 UTC
In the Brightness System Settings a button/option is missing to turn on "Automatic Brightness".
I had that option before with UBports Ubuntu Touch on a BQ Aquaris E5.

Ubuntu version 16.04. (2020-07-24)

**Comment by wayneoutthere** [comment] 2020-09-24 10:11
Definitely this is missing.  Definitely must be added.  This should be considered a 'bug' to me.  It looked like a lightning storm in my car at night ;)

**Comment by rubencarneiro** [comment] 2020-10-31 17:06
The config file is already whaiting on pr, bit to use that some sensor needs to be fixed first.

**Comment by mariogrip** [comment] 2020-11-10 22:52
@rubencarneiro a better way is to use the vendor overlays, this is new to android8+ devices, this requires a additional library to read these overlays as they are in .apk format. This way it will automatically work on all treble devices too. 

Fixed by https://github.com/ubports/repowerd/pull/14

**Comment by rubencarneiro** [comment] 2020-11-10 23:30
i will close the pr

**Comment by JamiKettunen** [comment] 2020-11-10 23:34
@rubencarneiro technically it is an issue still, let's close this when we can verifiably test that it is working :)

**Comment by GerryT11** [comment] 2020-12-02 20:27
same problem here.

Ubuntu 16.04 (OTA-14). Last updated 28.09.31 (sic!)

**Comment by rubencarneiro** [comment] 2020-12-02 20:37
Marius fixed commit a fix to repowerd, so lets jist wait.

**Comment by mariogrip** [comment] 2021-02-20 22:47
Merged ubports/repowerd#14

Please test :)

**Comment by JamiKettunen** [comment] 2021-02-21 17:33
@mariogrip Sadly the now visible toggle doesn't appear to work (i.e. enabling & setting high brightness and moving to darkness or setting low brightness and shining a bright light onto the sensor) even on a fully fresh install of Ubuntu Touch 16.04 development cannel build `2021-02-21/2`, are there some extra steps to get the toggle to "do something"?

**Comment by gbdomubpkm** [comment] 2021-02-24 23:33
I confirm that this function does not seem to work (RC 9). Activating the button only causes the manual brightness adjustment to be blocked.

**Comment by gbdomubpkm** [comment] 2021-03-16 13:52
Confirmed : not fixed in OTA-16

**Comment by gbdomubpkm** [comment] 2021-03-28 07:39
Seems fixed now in dev 305.

**Comment by mariogrip** [comment] 2021-03-28 15:55
Thanks! Closing this as it seems to be fixed in devel, please test and report back :)

**Closed by mariogrip** 2021-03-28 15:55 UTC
Labels: bug

**Comment by JamiKettunen** [comment] 2021-03-28 16:09
Yep, it's finally fixed as tested on Developent channel update `2021-03-28/3` on my end, thank you Marius!
