### ISSUE TITLE
 The "Cellular data" option does not connect to the internet anymore.

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#100] opened 2021-03-25 15:09 UTC
Ubuntu 16.04 (OTA-16):
After a time of using the phone the "Cellular data" option does not connect to the internet anymore.
I can switch the Celular data slider to on, but I do not get the "3G" symbol in the notification area.
Only after a reboot the connection to the internet can be activated again.

**Comment by wurzer** [comment] 2021-03-26 17:20
This issue should be fixed with OTA-16 Stable. I can't reproduce it any more. Could you please give more details?

- Is the data connection lost after moving (changing cells of the network)
- Is the data connection lost after traveling (roaming into another network)
- Is the data connection lost after standby (reactivating the device in the morning for instance)
- Can you tell us the country and or carrier?

**Comment by Stevie00911** [comment] 2021-04-05 13:07
Ubuntu 16.04 (OTA-16):
Last week I travelled through Germany via train, with many "changing cells of the Telekom network".
I often tried to activate the "Cellular data" option on and off and it allways connected to the internet, super!

Then after 3 days the "Cellular data" option did not connect to the internet anymore, see screen below.
So this happens absolutely sporadic and I can not reproduce when the "Cellular data" option works or not.
What I can assure, that it happens after some days of using the phone.

![20210402 Screenshot Vollaphone no internet](https://user-images.githubusercontent.com/45417818/113576663-43782800-9620-11eb-93de-2c573ae0f783.jpg)

**Comment by wurzer** [comment] 2021-04-05 16:25
Please contact our customer support to get this issue solved
https://volla.online/en/support/

**Comment by Stevie00911** [comment] 2021-04-07 15:35
After a restart of the device the internet connection via "Cellular data" works again,... for a while.
The network was lost without travelling, just staying "at home".

**Comment by wurzer** [comment] 2021-04-08 07:58
This is very strange, because I can't reproduce it on my device with even two SIM cards for Klarmobil (Deutsche Telekom) and Blau (E-Plus). We need to figure out, what the difference is. Are you able to provide us an ofono log? You can contact us directly to send us the file. 

How is your network strength at home? Maybe the is a difference.

**Comment by Stevie00911** [comment] 2021-04-18 13:59
I am sorry, I am not able to create an ofono log. 
This week I had this issue three times again.
My network strength is verry high, as you can see on the screen above.

**Comment by wurzer** [comment] 2021-05-14 14:43
Could you re-check this issue with the developer OTA channel? 
If not we would need another log to investigate.

**Comment by wurzer** [comment] 2021-05-14 16:30
If you can reproduce it you can run 

    sudo -s
    unset LD_LIBRARY_PATH
    /system/bin/logcat -b radio > logcat_radio.txt

Press Ctrl+C after some seconds and send us logcat_radio.txt file

**Comment by Stevie00911** [comment] 2021-05-15 11:15
@wurzer thank you for your message.
I changed now to the development OTA channel and istalled the "2021-05-14" version.

Pressing "Ctrl+C"? This was not possible with the touchscreen keyboard. 
So I plugged my PC keybord on the USB C jack of the vollaphone and it was recognized as a keyboard.

After opening the "Terminal" app I typed in your example and after "Ctrl+C" the terminal only shows "^C".
However I found a logcat_radio.txt file under "home" > "phablet" with 1.6 mb dated 15.05.2021:

[logcat_radio.txt](https://github.com/HelloVolla/ubuntu-touch-beta-tests/files/6486070/logcat_radio.txt)

I hope the logcat_radio.txt helps you out.
This is a very long log. It's lines begins with "05-15 04:41:45.985...".
What does the phone so early in the morning at 4:41 o'clock?
This topic behaviour is based under the Connection type "2G/3G".
Please consider also my new experience under development OTA (2021-05-14) I wrote under #71.

**Comment by wurzer** [comment] 2021-05-24 09:13
We have looked into the log. Your APN name is empty. 
`05-15 12:34:49.174   350   392 I AT      : [0] AT> AT+EAPNACT=1,"","default",0 (RIL_CMD_READER_4 tid:504414491888)`
However, connection seem to go through just fine from log.
So we can't derive the issue you have with the network connection.
Did you update to OTA-17?

**Comment by Stevie00911** [comment] 2021-07-02 08:24
UT OTA 17
I added the APN Name "Telekom", however no changes remarkable.

With OTA 17 under 3G "Cellular data" loss did happen only very rarely.  

With OTA 17 under 4G "Cellular data" loss did happen only very rarely,
but I could only check the "L" Symbol in the infobar, because "Cellular data" still not work.

**Comment by Stevie00911** [comment] 2021-07-29 14:19
UT OTA 18

With OTA 18 the "Cellular data" option is now stable under 4G.
I can now close this issue.

**Closed** 2021-07-29 14:21 UTC
Labels: bug
