### ISSUE TITLE
Switch form WiFi to cellular network is only possible with a reboot

### ISSUE THREAD

**Issue by wurzer** [HelloVolla/ubuntu-touch-beta-tests#30] opened 2020-08-09 04:42 UTC
A beta user reports: "If I switch from WiFi to cellular data fails. As a work-around I reboot with WiFi off will solve it."

**Comment by 0312birdzhang** [comment] 2020-09-07 14:33
Can't reproduce, Ubuntu version 16.04 (2020-09-05),  and "2G/3G/4G" option is there.

**Comment by Stevie00911** [comment] 2020-09-07 15:14
Yes, the "2G/3G/4G" option is there and can be selected, but with nearly no internet connection (cellular data).
My carrier is Deutsche Telekom and I expect a LTE (4G) connection.
When the "2G/3G/4G" option and cellular data is selected (after a reboot, of course) it is possible to contact the Ubuntu update channel (searching for updates took 1 minute), but the Morph browser only shows "no network available" pages.
So there might be an internet connection with the "2G/3G/4G" option, but is is absolutely too slow.   
Ubuntu version 16.04 (2020-09-07)

**Comment by JamiKettunen** [comment] 2020-10-10 19:07
After extensive testing (same steps as previously) on development channel build `2020-10-09/2` I still cannot reproduce this, closing as the originally experienced issue seems to be related to something else than switching between Wi-Fi and cellular networks directly.
Detailed steps to reproduce always help massively!

**Closed by JamiKettunen** 2020-10-10 19:07 UTC
Labels: bug, help wanted
