### ISSUE TITLE
Carrier registeration not re-established after flight mode

### ISSUE THREAD

**Issue by TellingBerto** [HelloVolla/ubuntu-touch-beta-tests#51] opened 2020-09-26 15:36 UTC
Hello.

1. Boot the device.
2. Enter in SIM pin.
-> Carrier registration takes place successfully.
3. Enter in device pin.
4. Open network settings via Network icon in indicator bar.
-> Verify on the same screen the name of the carrier is displayed before the triangle.
5. Activate celluar data.
-> Verify on network setting screen the indicator for cellular data is displayed after the triangle.
-> Verify on the indicator bar the indicator for cellular data is displayed after the triangle.
-> Check data connection with browser and verify that any website can be displayed.

6. Activate flight mode.
-> Carrier name disappeared (log off) triangle is inactive.
7. Deactivate flight mode.
-> "Searching" displayed, triangle remains inactive.

**Result:** 
Carrier registration lost.

**Comment by Stevie00911** [comment] 2020-10-02 10:24
My Vollaphone has the same behaviour.

Additionally I often loose the carrier registration after a new OTA upgrade. 
Switching off and restarting a view times brings the carrier registration back.  

Ubuntu 16.04 (2020-10-02) dev

**Comment by NotKit** [comment] 2020-10-12 17:51
Should be resolved as version 30 of development OTA upgrade.

**Comment by TellingBerto** [comment] 2020-10-13 18:54
Retest.
Ubuntu 16.04 (2020-10-13/2) dev

Result: Fail

    Boot the device.

    Enter in SIM pin.
    -> Carrier registration is taking place successfully.

    Enter in device pin.

    Open network settings via Network icon in indicator bar.
    -> Verify on the same screen the name of the carrier is displayed before the triangle.

    Activate cellular data.
    -> Verify on network setting screen the indicator for cellular data is displayed after the triangle.
    -> Verify on the indicator bar the indicator for cellular data is displayed after the triangle.
    -> Check data connection with browser and verify that any website can be displayed.

    Activate flight mode.
    -> Carrier name disappeared (log off) triangle is inactive.

    Deactivate flight mode.
    -> "Searching" displayed, triangle remains inactive.
    -> After search has stopped "no signal" is displayed before the triangle.
    -> Indicator for cellular data is displayed after the triangle.
    -> Carrier name still available in the details for network
    -> Manually searching possible but does not solve the issue.

*Result:*
Carrier registration lost by activating the flight mode.

**Comment by JamiKettunen** [comment] 2020-10-14 17:59
Since the original issue as per the title of this issue has been confirmed fixed, I'll go ahead and close this one :)

**Closed by JamiKettunen** 2020-10-14 17:59 UTC
